//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adversting_Company.dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductXCompany
    {
        public int Id_company { get; set; }
        public int Id_product { get; set; }
        public int id { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Product Product { get; set; }
    }
}
